# Name of website
title: Linux User Group Hannover
# Short description of your site
email: lug-hannover <ät> tutanota.de
description: > # Ignoriere neue Zeilen bis einschl. "baseurl:"
    Aktuelle Termine, Themen und Veranstaltungen der Linux User Group Hannover.

baseurl: "" # Der Pfad zur Seite, z.B. /blog
url: "/" # Der Hostname oder Wurzelverzeichnis der Website
twitter_username: lughannover

github: Homepage
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-minimal
gfm_quirks: paragraph_end
