# Name of website
title: My website
# Short description of your site
description: A virtual proof that I'm awesome
github: 
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-minimal
gfm_quirks: paragraph_end
