# Name of website
title: Linux User Group Hannover
# Short description of your site
description: Aktuelle Termine, Themen und Veranstaltungen der Linux User Group Hannover.
github: Homepage
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-minimal
gfm_quirks: paragraph_end
